// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadOutput(arg1) {
  return window['go']['wails']['AuditService']['LoadOutput'](arg1);
}

export function Query(arg1) {
  return window['go']['wails']['AuditService']['Query'](arg1);
}
