// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function LoadOutput(arg1:number):Promise<Array<wails.AuditOutputSegmentDTO>>;

export function Query(arg1:string):Promise<Array<wails.AuditEventDTO>>;
