// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function ClearHistory(arg1:string):Promise<void>;

export function DeleteHistoryEntry(arg1:number):Promise<void>;

export function ListHistory(arg1:wails.HistoryQueryDTO):Promise<Array<wails.HistoryEntryDTO>>;
