// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory(arg1) {
  return window['go']['wails']['HistoryService']['ClearHistory'](arg1);
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['wails']['HistoryService']['DeleteHistoryEntry'](arg1);
}

export function ListHistory(arg1) {
  return window['go']['wails']['HistoryService']['ListHistory'](arg1);
}
