// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function DeleteHost(arg1:string):Promise<void>;

export function GetHost(arg1:string):Promise<wails.HostDTO>;

export function ListHosts():Promise<Array<wails.HostDTO>>;

export function ListLabels():Promise<Array<string>>;

export function SaveHost(arg1:wails.HostInputDTO):Promise<wails.HostDTO>;

export function SetHostSecret(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:string):Promise<wails.TestResultDTO>;
