// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForKeyFile() {
  return window['go']['wails']['HostService']['BrowseForKeyFile']();
}

export function DeleteHost(arg1) {
  return window['go']['wails']['HostService']['DeleteHost'](arg1);
}

export function GetHost(arg1) {
  return window['go']['wails']['HostService']['GetHost'](arg1);
}

export function ListHosts() {
  return window['go']['wails']['HostService']['ListHosts']();
}

export function ListLabels() {
  return window['go']['wails']['HostService']['ListLabels']();
}

export function SaveHost(arg1) {
  return window['go']['wails']['HostService']['SaveHost'](arg1);
}

export function SetHostSecret(arg1, arg2) {
  return window['go']['wails']['HostService']['SetHostSecret'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['wails']['HostService']['TestConnection'](arg1);
}
