// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Copy(arg1, arg2) {
  return window['go']['wails']['LocalFSService']['Copy'](arg1, arg2);
}

export function HomeDir() {
  return window['go']['wails']['LocalFSService']['HomeDir']();
}

export function ListDir(arg1) {
  return window['go']['wails']['LocalFSService']['ListDir'](arg1);
}

export function Mkdir(arg1) {
  return window['go']['wails']['LocalFSService']['Mkdir'](arg1);
}

export function Move(arg1, arg2) {
  return window['go']['wails']['LocalFSService']['Move'](arg1, arg2);
}

export function Remove(arg1) {
  return window['go']['wails']['LocalFSService']['Remove'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['wails']['LocalFSService']['Rename'](arg1, arg2);
}

export function Roots() {
  return window['go']['wails']['LocalFSService']['Roots']();
}

export function Stat(arg1) {
  return window['go']['wails']['LocalFSService']['Stat'](arg1);
}
