// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function Copy(arg1:Array<string>,arg2:string):Promise<void>;

export function HomeDir():Promise<string>;

export function ListDir(arg1:string):Promise<Array<wails.RemoteEntryDTO>>;

export function Mkdir(arg1:string):Promise<void>;

export function Move(arg1:Array<string>,arg2:string):Promise<void>;

export function Remove(arg1:string):Promise<void>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function Roots():Promise<Array<string>>;

export function Stat(arg1:string):Promise<wails.RemoteEntryDTO>;
