// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function KillControl(arg1:string):Promise<void>;

export function ListClients():Promise<Array<wails.MCPClientDTO>>;

export function ListDelegations():Promise<Array<wails.DelegationDTO>>;

export function RespondCommandApproval(arg1:string,arg2:boolean):Promise<void>;

export function RespondConnectApproval(arg1:string,arg2:boolean):Promise<void>;

export function RespondConnectionScopeApproval(arg1:string,arg2:boolean):Promise<void>;

export function RespondControlApproval(arg1:string,arg2:boolean):Promise<void>;

export function RespondPairing(arg1:string,arg2:boolean):Promise<void>;

export function RevokeClient(arg1:string):Promise<void>;
