// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KillControl(arg1) {
  return window['go']['wails']['MCPApprovalService']['KillControl'](arg1);
}

export function ListClients() {
  return window['go']['wails']['MCPApprovalService']['ListClients']();
}

export function ListDelegations() {
  return window['go']['wails']['MCPApprovalService']['ListDelegations']();
}

export function RespondCommandApproval(arg1, arg2) {
  return window['go']['wails']['MCPApprovalService']['RespondCommandApproval'](arg1, arg2);
}

export function RespondConnectApproval(arg1, arg2) {
  return window['go']['wails']['MCPApprovalService']['RespondConnectApproval'](arg1, arg2);
}

export function RespondConnectionScopeApproval(arg1, arg2) {
  return window['go']['wails']['MCPApprovalService']['RespondConnectionScopeApproval'](arg1, arg2);
}

export function RespondControlApproval(arg1, arg2) {
  return window['go']['wails']['MCPApprovalService']['RespondControlApproval'](arg1, arg2);
}

export function RespondPairing(arg1, arg2) {
  return window['go']['wails']['MCPApprovalService']['RespondPairing'](arg1, arg2);
}

export function RevokeClient(arg1) {
  return window['go']['wails']['MCPApprovalService']['RevokeClient'](arg1);
}
