// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RespondCommandApproval(arg1:string,arg2:boolean):Promise<void>;

export function RespondConnectApproval(arg1:string,arg2:boolean):Promise<void>;

export function RespondControlApproval(arg1:string,arg2:boolean):Promise<void>;

export function RespondPairing(arg1:string,arg2:boolean):Promise<void>;
