// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['wails']['SessionService']['CloseSession'](arg1);
}

export function CreateLocalSession(arg1) {
  return window['go']['wails']['SessionService']['CreateLocalSession'](arg1);
}

export function CreateSSHDirectSession(arg1) {
  return window['go']['wails']['SessionService']['CreateSSHDirectSession'](arg1);
}

export function CreateSSHSession(arg1) {
  return window['go']['wails']['SessionService']['CreateSSHSession'](arg1);
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['wails']['SessionService']['ResizeSession'](arg1, arg2, arg3);
}

export function RespondHostKey(arg1, arg2) {
  return window['go']['wails']['SessionService']['RespondHostKey'](arg1, arg2);
}

export function WriteSession(arg1, arg2) {
  return window['go']['wails']['SessionService']['WriteSession'](arg1, arg2);
}
