// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function CreateLocalSession(arg1:wails.LocalSessionOpts):Promise<wails.SessionInfoDTO>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function WriteSession(arg1:string,arg2:string):Promise<void>;
