// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function AppInfo():Promise<wails.AppInfoDTO>;

export function GetAll():Promise<Record<string, string>>;

export function Set(arg1:string,arg2:string):Promise<void>;
