// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['wails']['SettingsService']['AppInfo']();
}

export function GetAll() {
  return window['go']['wails']['SettingsService']['GetAll']();
}

export function Set(arg1, arg2) {
  return window['go']['wails']['SettingsService']['Set'](arg1, arg2);
}
