// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPeerByAddress(arg1, arg2, arg3) {
  return window['go']['wails']['ShareService']['AddPeerByAddress'](arg1, arg2, arg3);
}

export function DisableSharing() {
  return window['go']['wails']['ShareService']['DisableSharing']();
}

export function EnableSharing(arg1) {
  return window['go']['wails']['ShareService']['EnableSharing'](arg1);
}

export function FetchSharedHosts(arg1) {
  return window['go']['wails']['ShareService']['FetchSharedHosts'](arg1);
}

export function ImportSharedHost(arg1, arg2) {
  return window['go']['wails']['ShareService']['ImportSharedHost'](arg1, arg2);
}

export function ListClients() {
  return window['go']['wails']['ShareService']['ListClients']();
}

export function ListPeers() {
  return window['go']['wails']['ShareService']['ListPeers']();
}

export function PairWithPeer(arg1, arg2) {
  return window['go']['wails']['ShareService']['PairWithPeer'](arg1, arg2);
}

export function RemovePeer(arg1) {
  return window['go']['wails']['ShareService']['RemovePeer'](arg1);
}

export function RespondPairing(arg1, arg2) {
  return window['go']['wails']['ShareService']['RespondPairing'](arg1, arg2);
}

export function RevokeClient(arg1) {
  return window['go']['wails']['ShareService']['RevokeClient'](arg1);
}

export function SetSharedHosts(arg1) {
  return window['go']['wails']['ShareService']['SetSharedHosts'](arg1);
}

export function Status() {
  return window['go']['wails']['ShareService']['Status']();
}
