// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function AddPeerByAddress(arg1:string,arg2:number,arg3:string):Promise<void>;

export function DisableSharing():Promise<void>;

export function EnableSharing(arg1:Array<string>):Promise<wails.ShareStatusDTO>;

export function FetchSharedHosts(arg1:string):Promise<Array<wails.SharedHostDTO>>;

export function ListClients():Promise<Array<wails.ShareClientDTO>>;

export function ListPeers():Promise<Array<wails.PeerViewDTO>>;

export function PairWithPeer(arg1:string,arg2:string):Promise<void>;

export function RemovePeer(arg1:string):Promise<void>;

export function RespondPairing(arg1:string,arg2:boolean):Promise<void>;

export function RevokeClient(arg1:string):Promise<void>;

export function SetSharedHosts(arg1:Array<string>):Promise<void>;

export function Status():Promise<wails.ShareStatusDTO>;
