// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function BrowseForDownloadDirectory():Promise<string>;

export function BrowseForUploadFiles():Promise<Array<string>>;

export function CancelTransfer(arg1:string):Promise<void>;

export function CancelZmodem(arg1:string):Promise<void>;

export function Chmod(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Download(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<Array<string>>;

export function HomeDir(arg1:string):Promise<string>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<Array<wails.RemoteEntryDTO>>;

export function ListTasks():Promise<Array<wails.TaskInfoDTO>>;

export function Mkdir(arg1:string,arg2:string):Promise<void>;

export function Remove(arg1:string,arg2:string):Promise<void>;

export function Rename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartZmodemSend(arg1:string,arg2:Array<string>):Promise<string>;

export function StatRemote(arg1:string,arg2:string):Promise<wails.RemoteEntryDTO>;

export function Upload(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<Array<string>>;
