// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForDownloadDirectory() {
  return window['go']['wails']['TransferService']['BrowseForDownloadDirectory']();
}

export function BrowseForUploadFiles() {
  return window['go']['wails']['TransferService']['BrowseForUploadFiles']();
}

export function CancelTransfer(arg1) {
  return window['go']['wails']['TransferService']['CancelTransfer'](arg1);
}

export function CancelZmodem(arg1) {
  return window['go']['wails']['TransferService']['CancelZmodem'](arg1);
}

export function Chmod(arg1, arg2, arg3) {
  return window['go']['wails']['TransferService']['Chmod'](arg1, arg2, arg3);
}

export function CopyRemote(arg1, arg2, arg3) {
  return window['go']['wails']['TransferService']['CopyRemote'](arg1, arg2, arg3);
}

export function Download(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['TransferService']['Download'](arg1, arg2, arg3, arg4);
}

export function HomeDir(arg1) {
  return window['go']['wails']['TransferService']['HomeDir'](arg1);
}

export function ListRemoteDir(arg1, arg2) {
  return window['go']['wails']['TransferService']['ListRemoteDir'](arg1, arg2);
}

export function ListTasks() {
  return window['go']['wails']['TransferService']['ListTasks']();
}

export function Mkdir(arg1, arg2) {
  return window['go']['wails']['TransferService']['Mkdir'](arg1, arg2);
}

export function Remove(arg1, arg2) {
  return window['go']['wails']['TransferService']['Remove'](arg1, arg2);
}

export function Rename(arg1, arg2, arg3) {
  return window['go']['wails']['TransferService']['Rename'](arg1, arg2, arg3);
}

export function StartZmodemSend(arg1, arg2) {
  return window['go']['wails']['TransferService']['StartZmodemSend'](arg1, arg2);
}

export function StatRemote(arg1, arg2) {
  return window['go']['wails']['TransferService']['StatRemote'](arg1, arg2);
}

export function Upload(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['TransferService']['Upload'](arg1, arg2, arg3, arg4);
}
